alexevanczuk/packs

Cargo.toml
scripts/packwerk_parity_checker.rb
src/packs/cli.rs
src/packs/parser.rs

- write another failing test
- make tests pass
- remove dbg
- fix merge issue
- look at packs for now
- fix bug

Support some associations

---

README.md
src/packs/parser.rs

- write fialing test
- fix other test
- address clippy warning
- try to make test pass
- clippy
- make another tests pass
- Fix typo
- make tests pass
- fix some edge cases in association detection

Cover some reference extraction cases

---

Cargo.toml
src/packs/configuration.rs
src/packs/inflector_shim.rs

- Fix issue with root pack not existing and a constant with unknown origin
- add some more debugging, clean up some comments
- use supported inflector library

Use supported inflector library

---

Cargo.toml
src/packs/inflector_shim.rs
src/packs/parser/ruby/packwerk/constant_resolver.rs

- Use ruby_inflector
- bump version

Support parsing constants with numerics

---

src/packs/package_todo.rs

Fix issue serializing the name of the root pack in package_todo.yml files

---

BENCHMARKS.md
dev/notes.md
src/packs/checker.rs
src/packs/configuration.rs
src/packs/package_todo.rs
src/packs/parser/ruby/packwerk/constant_resolver.rs
src/packs/per_file_cache.rs
src/packs/walk_directory.rs

- Refactor walk_directory to return a result object
- update readme
- debug perf events separately
- add directions on updated benchmarking
- add benchmarks

Improve docs on benchmarking

---

src/packs.rs
src/packs/checker/reference.rs
src/packs/constant_resolver.rs
src/packs/parsing/ruby/experimental.rs
src/packs/parsing/ruby/experimental/constant_resolver.rs
src/packs/parsing/ruby/zeitwerk/constant_resolver.rs
src/packs/parsing/ruby/zeitwerk/mod.rs

- start making consetant resolver reeturn a vec of definitions
- implement experimental constant resolver

Change ConstantResolver API to allow for multiple definitions for experimental parser

---

Cargo.toml
README.md
src/packs/checker.rs
src/packs/cli.rs
tests/list_unnecessary_dependencies.rs

- extract get_all_references into its own method
- Move cach usage to get_all_references
- Add packs list-unnecessary-dependencies CLI command
- update readme
- bump version

Add packs list-unnecessary-dependencies

---

README.md

- extract get_all_references into its own method
- Move cach usage to get_all_references
- Add Kudos section to README.md

Add kudos to README.md

---

Cargo.toml
README.md
src/packs.rs
src/packs/checker.rs
src/packs/configuration.rs
src/packs/parsing/erb/experimental/parser.rs
src/packs/parsing/erb/packwerk.rs
src/packs/parsing/erb/packwerk/parser.rs
src/packs/parsing/mod.rs
src/packs/parsing/ruby/experimental.rs
src/packs/parsing/ruby/experimental/parser.rs
src/packs/parsing/ruby/packwerk.rs
src/packs/parsing/ruby/packwerk/parser.rs
src/packs/parsing/ruby/parse_utils.rs

- Pull out association method names vec
- pass configuration through to parser
- pass configuration through to other parser functions
- update readme
- bump version

Support custom associations

---

Cargo.toml
README.md
src/packs/checker.rs
src/packs/checker/architecture.rs
src/packs/checker/dependency.rs
src/packs/checker/privacy.rs
src/packs/checker/visibility.rs
tests/check_test.rs
tests/fixtures/uses_strict_mode/package.yml
tests/fixtures/uses_strict_mode/packs/bar/app/services/bar.rb
tests/fixtures/uses_strict_mode/packs/bar/package.yml
tests/fixtures/uses_strict_mode/packs/foo/app/services/foo.rb
tests/fixtures/uses_strict_mode/packs/foo/package.yml
tests/fixtures/uses_strict_mode/packs/foo/package_todo.yml
tests/fixtures/uses_strict_mode/packwerk.yml

Closes #65
- add noop debug statements
- violation should record if strict mode is on for that violation
- Revert "violation should record if strict mode is on for that violation"
- pass checkers in
- add checker interface method
- make tests pass
- bump version

Support strict mode

---

Cargo.toml
src/packs/checker/privacy.rs

Fix issue with public constant

---

src/packs/checker.rs
tests/check_test.rs
tests/fixtures/contains_package_todo/packs/foo/app/services/other_foo.rb
tests/fixtures/contains_package_todo/packs/foo/package_todo.yml

Only consider violations stale if they exist in inputted files

---

Cargo.toml
README.md
src/packs/cli.rs
src/packs/configuration.rs
src/packs/parsing/mod.rs

- print files if print_files is configured as true
- clean up how configuration is set
- add new arg
- bump version
- add note

Print files to console with CLI flag

---

src/packs/caching/cache.rs
src/packs/caching/mod.rs
src/packs/caching/noop_cache.rs
src/packs/caching/per_file_cache.rs
src/packs/configuration.rs
src/packs/parsing/mod.rs

- Tidy CacheEntry
- pull cache into separate file
- move mod declarations up

Tidy up some things in cache

---

Cargo.toml
src/packs/checker.rs
src/packs/checker/architecture.rs
src/packs/checker/dependency.rs
src/packs/checker/privacy.rs
src/packs/checker/reference.rs
src/packs/checker/visibility.rs
src/packs/pack_set.rs
src/packs/package_todo.rs

- provide error messages to getting package
- cargo fmt is not working
- wip
- tidy up checkers
- improve error message in for_file

Improve error messages related to not being able to find pack for file

---

Cargo.toml
src/packs.rs
src/packs/cli.rs

This makes it simpler to call rust from ruby

Move CLI to use packs module API

---

Cargo.toml
src/packs.rs
src/packs/checker.rs
src/packs/cli.rs
src/packs/package_todo.rs

This can be used from the ruby gem to call APIs like `update`.

Add public API to get configuration

---

.github/workflows/ci.yml
Cargo.toml
src/packs.rs
src/packs/cli.rs
src/packs/pack.rs
tests/common/mod.rs
tests/create_test.rs

- Add pks create CLI API
- bump version

Add pks create function

---

Cargo.toml
README.md
src/packs.rs
src/packs/cli.rs
src/packs/pack.rs
src/packs/pack_set.rs
tests/add_dependency_test.rs
tests/common/mod.rs
tests/create_test.rs
tests/fixtures/app_with_missing_dependency/packs/bar/package.yml
tests/fixtures/app_with_missing_dependency/packs/baz/package.yml
tests/fixtures/app_with_missing_dependency/packs/foo/package.yml
tests/fixtures/app_with_missing_dependency/packwerk.yml

- Add pks add-dependency CLI API
- run some tests in serial
- trim trailing slash from pack name
- bump verison
- update readme

Add pks add-dependency CLI API

---

src/packs/file_utils.rs
src/packs/parsing/ruby/experimental/parser.rs
src/packs/parsing/ruby/packwerk/parser.rs
src/packs/walk_directory.rs

- cargo clippy --fix -- -D warnings
- cargo fmt --all

Fix CI related to updated rust version

---

src/packs/checker.rs

Breaking up the `check_all`  function into methods using the builder pattern.

Breaking check_all into smaller methods

---

src/packs/parsing/ruby/inflector_shim.rs

Instead of replacing detected acronyms with their calculated upper case value, let's use the string as specified in inflections.rb. This should match Rails' behaviour better.

Retain inflection case from inflection.rb

---

src/packs/configuration.rs
src/packs/pack.rs
src/packs/pack_set.rs
src/packs/walk_directory.rs

Replacing the `panic!`s in `from_path` with returning Errors

from_path returns anyhow::Result

---

src/packs.rs
src/packs/checker.rs
src/packs/cli.rs
src/packs/configuration.rs
src/packs/constant_dependencies.rs
src/packs/pack.rs
src/packs/raw_configuration.rs

Removing the panics in RawConfiguration in favor of return anyhow::Result

Converting RawConfiguration to user anyhow::Result

---

src/packs/caching/cache.rs
src/packs/caching/noop_cache.rs
src/packs/caching/per_file_cache.rs
src/packs/parsing/mod.rs

Cache `from_empty` and `write` now return anyhow:Result

Cache write returns result

---

src/packs/checker/architecture.rs
src/packs/checker/dependency.rs
src/packs/checker/folder_visibility.rs
src/packs/checker/privacy.rs
src/packs/checker/reference.rs
src/packs/checker/visibility.rs

`reference::referencing_pack` returns anyhow::Result

Referencing_pack returns result

---

Cargo.toml
src/packs/checker.rs

Fixes https://github.com/alexevanczuk/packs/issues/190

Put a new line between violation output

---

Cargo.toml

version 0.2.6

---

Cargo.toml

bumping to 0.2.7

---

INSTALLATION.md
src/packs.rs
src/packs/bin_locater.rs
src/packs/checker.rs

This is a temporary solution for providing the actual binary path to pks in the "stale" message.
Definitely open to feedback!

Stale message includes bin/pks if it exists

---

src/packs/checker/folder_privacy.rs
tests/folder_privacy_test.rs

Small tweak to folder privacy error message for clarity.

Updating folder privacy violation error text

---

Cargo.toml
src/packs/parsing/ruby/zeitwerk/mod.rs

- **add failing test**
- **Fix test**
- **make more terse**
- **bump version**

Patch corrupt cache issue
