- Cargo.toml
- src/packs/inflector_shim.rs
- src/packs/parser/ruby/packwerk/constant_resolver.rs
- src/packs/parser/ruby/packwerk/extractor.rs
- tests/fixtures/app_with_inflections/app/services/some_api_class.rb
- tests/fixtures/app_with_inflections/config/initializers/inflections.rb
- tests/fixtures/app_with_inflections/packwerk.yml
This is a *first* attempt at trying to support parsing `config/initializers/inflections.rb`.
For example, if there is an acronym `API`, `to_class_case('some_api_error')` should be `SomeAPIError`.
We'll likely need to iterate on this!
> Support Inflections

- README.md
- src/packs/parser/ruby/packwerk/constant_resolver.rs
- src/packs/per_file_cache.rs
- tests/fixtures/app_with_inflections/app/services/my_module/some_csv_class.rb
- tests/fixtures/app_with_inflections/config/initializers/inflections.rb
- update readme slightly
- fix coupling of inflections to name of yielded argument and use of double vs single quoted strings
> Fix coupling of inflections to name of yielded param in inflections.rb and use of double vs. single quotes

- src/packs.rs
- src/packs/checker/privacy.rs
- src/packs/configuration.rs
- simplify privacy tests to create pack structs
- fix bug
- allow overriding public folder
- default folder should be app/public not just public
> Allow for configurable public folders for privacy checker

- Cargo.toml
- src/packs/walk_directory.rs
Replace [glob-match](https://github.com/devongovett/glob-match) with [globset](https://github.com/BurntSushi/ripgrep/tree/master/crates/globset) because https://github.com/devongovett/glob-match/issues/9 prevents some of the Ruby files from being included.
The performance is roughly the same. `packs2` is the version with the patch.
```
$ hyperfine --runs 50 'packs check' 'packs2 check'
Benchmark 1: packs check
Time (mean ± σ):     947.9 ms ±  21.3 ms    [User: 1440.1 ms, System: 2817.1 ms]
Range (min … max):   910.4 ms … 1019.3 ms    50 runs
Benchmark 2: packs2 check
Time (mean ± σ):     938.9 ms ±  21.9 ms    [User: 1426.8 ms, System: 2826.5 ms]
Range (min … max):   907.1 ms … 1001.6 ms    50 runs
Summary
packs2 check ran
1.01 ± 0.03 times faster than packs check
```
Note on …
> Replace glob-match with globset

- BENCHMARKS.md
- src/packs/checker.rs
- src/packs/parser/ruby/packwerk/constant_resolver.rs
- src/packs/walk_directory.rs
- Borrow rather than clones variables in constant resolver
- avoid trimming start matches unless we need to
- update benchmarks
> Borrow rather than clone memory in constant_resolver

- src/packs.rs
- src/packs/parser.rs
- src/packs/parser/erb/packwerk.rs
- src/packs/parser/erb/packwerk/extractor.rs
- src/packs/parser/ruby/packwerk.rs
- src/packs/parser/ruby/packwerk/extractor.rs
- src/packs/per_file_cache.rs
- Move UnresolvedReferences to better place
- Move other structs into parser
- remove unused struct
> Move unresolved reference struct to better home

- Cargo.toml
- dev/notes.md
- src/packs/configuration.rs
- src/packs/parsing/ruby/packwerk/constant_resolver.rs
This saves some time on building the constant resolver.
This in particular makes `packs check with/one/or/few/paths.rb` pretty fast (half second).
I'm also exploring building the constant resolver incrementally when walking the directory, but haven't found a way to do this that isn't *less* performant than the current implementation. For example, here's an alternate implementation: https://github.com/alexevanczuk/packs/pull/37
However, that implementation is actually less performant than the current one. It would be helpful to move towards that style of implementation (building it incrementally) because it would allow us to gracefully migrate to an approach where we parse files for definitions.
> Use cache for constant resolver

- Cargo.toml
- src/packs/configuration.rs
- src/packs/parsing/ruby/packwerk/constant_resolver.rs
- src/packs/parsing/ruby/zeitwerk_utils.rs
This gets us ready to allow a constant resolver to be more easily initialized from a set of processed files for the alternate parser.
> Move most of ConstantResovler to zeitwerk_utils

- Cargo.toml
- README.md
- dev/notes.md
- src/main-alt.rs
- src/main.rs
- src/packs/checker.rs
- src/packs/cli.rs
- src/packs/configuration.rs
- src/packs/logger.rs
- src/packs/package_todo.rs
- src/packs/parsing/ruby/packwerk/constant_resolver.rs
- src/packs/parsing/ruby/zeitwerk_utils.rs
- src/packs/walk_directory.rs
This allows the CLI to be run with `packs --debug check`, which makes debugging where time is spent simpler.
> Improve logging with --debug flag 

- Cargo.toml
- EXPERIMENTAL_PARSER_USAGE.md
- README.md
- dev/notes.md
- src/packs.rs
- src/packs/checker.rs
- src/packs/cli.rs
- src/packs/file_utils.rs
- src/packs/parsing.rs
- src/packs/parsing/erb/experimental.rs
- src/packs/parsing/erb/experimental/parser.rs
- src/packs/parsing/erb/mod.rs
- src/packs/parsing/ruby/experimental.rs
- src/packs/parsing/ruby/experimental/parser.rs
- src/packs/parsing/ruby/mod.rs
- src/packs/parsing/ruby/packwerk/constant_resolver.rs
- src/packs/parsing/ruby/zeitwerk_utils.rs
- src/packs/per_file_cache.rs
- tests/check_test.rs
- tests/fixtures/simple_app/packs/bar/app/services/bar.rb
- tests/update_test.rs
This enables an alpha version of the experimental parser, which allows `packwerk` to be used in non-rails apps.
> Spike on experimental parser

- src/packs.rs
- src/packs/caching.rs
- src/packs/checker.rs
- src/packs/configuration.rs
- src/packs/noop_cache.rs
- src/packs/parsing.rs
- src/packs/per_file_cache.rs
- src/packs/reference_graph_builder.rs
- move cache to own module
- simplify caching so it simply has a get and write function
- rename CachableFile to CacheMiss
- refactor code to use enum of cache result
- add file_name_digest
- rename cache miss to empty cache entry
- rename related function
- WIP reference_graph_builder
- Revert "WIP reference_graph_builder"
- remove commented out process_file
> Simplify cache trait

- Cargo.toml
- src/packs/raw_configuration.rs
- src/packs/walk_directory.rs
- tests/fixtures/simple_app/node_modules/subfolder/file.rb
A user reported a really nasty bug where `delete-cache` deleted the current directory if there is no `packwerk.yml` file.
The reason for this is that if there is no `packwerk.yml` file, the rust implementation uses the derived "default" implementation of  the `RawConfiguration` struct. The default implementation of the string for `cache_directory` is an empty string (similarly, if it were a `PathBuf`, it'd be an empty path but).
I had thought that the derived property for `Default` would respect the defaults set by serde, but turns out that's not the case...!
- Fix test
> Fix issue with default packwerk.yml contents not properly loading if packwerk.yml does not exist

- src/packs/parsing.rs
- src/packs/parsing/ruby/experimental.rs
- src/packs/parsing/ruby/experimental/parser.rs
- src/packs/parsing/ruby/packwerk/parser.rs
`Definition` does not need a `namespace_path` attribute. It's never meaningfully read and conceptually not relevant to a definition.
> Simplify Definition struct

- src/packs.rs
- src/packs/checker.rs
- src/packs/parsing.rs
- src/packs/parsing/ruby/experimental.rs
- src/packs/parsing/ruby/experimental/parser.rs
- src/packs/parsing/ruby/packwerk/constant_resolver.rs
- src/packs/parsing/ruby/packwerk/parser.rs
- src/packs/parsing/ruby/zeitwerk_utils.rs
- src/packs/per_file_cache.rs
- Rename Definition to ParsedDefinition
- rename constant to ConstantDefinition
- rename constant resolver attribute
- remove unused parameter
> Naming updates to ConstantResolver

- src/packs/parsing/ruby/constant_resolver.rs
- src/packs/parsing/ruby/experimental.rs
- src/packs/parsing/ruby/experimental/parser.rs
- src/packs/parsing/ruby/mod.rs
- src/packs/parsing/ruby/packwerk/parser.rs
- src/packs/parsing/ruby/parse_utils.rs
- src/packs/parsing/ruby/zeitwerk_utils.rs
- fetch_node_location
- loc_to_range
- fetch_const_name
- Make constant definitions inserted by each parser have consistent leading colons
- move get_definition_from in
- fetch_casgn_name
- move out get_reference_from_active_record_association
- remove extra line
- remove debug statement
- fix on_casgn error with experimental parser
- extract out from on_casgn
- remove dbg
- remove dbgs
> Extract out common methods in AST parsing

- src/lib.rs
- src/packs.rs
- src/packs/checker.rs
- src/packs/checker/reference.rs
- src/packs/constant_resolver.rs
- src/packs/parsing/ruby/experimental.rs
- src/packs/parsing/ruby/zeitwerk/constant_resolver.rs
- src/packs/parsing/ruby/zeitwerk/mod.rs
- Create constant_resolver trait
- Move ConstantDefinition into constant_resolver module
- separate out the resolve method so it can come from the trait
- attempt to pass around instances of the trait rather than the zeitwerk constant resolver itself
- fix clippy
- do not clone unresolved ref location
- combine conditionals
- update var name
- move things that do not change based on constant resolution to the top
- add line
- mvoe reference into its own module
- move implementation into same module
- make Reference::from_unresolved_reference return an array of references
- refactor method part 1
- refactor method part 2
> Allow ConstantResolver to be passed around as a trait to permit multiple implementations

- src/packs/checker.rs
- src/packs/checker/architecture.rs
- src/packs/checker/dependency.rs
- src/packs/checker/privacy.rs
- src/packs/checker/reference.rs
- src/packs/checker/visibility.rs
- wip
- do not use lifetimes on reference
> Remove lifetimes from References so using across threads and closures is simpler

- Cargo.toml
- src/packs/checker.rs
- src/packs/checker/dependency.rs
- src/packs/cli.rs
- tests/check_test.rs
- tests/validate_test.rs
Perhaps later we can choose one of the following options:
1) Change packwerk to permit a flag to turn cycle detection on or off (`packs check` can respect that flag)
2) Change `packs` to read a flag to turn cycle detection ON (`packs check` would then do cycle detection, although this would diverge from packwerk slightly)
For now, we'll keep things separate to continue to emulate packwerk and make adoption simpler.
> Move cycle detection into validate for now to emulate packwerk

- src/packs/checker.rs
- src/packs/package_todo.rs
- tests/check_test.rs
- tests/common/mod.rs
- tests/fixtures/contains_stale_violations/packs/bar/app/services/bar.rb
- tests/fixtures/contains_stale_violations/packs/bar/package.yml
- tests/fixtures/contains_stale_violations/packs/bar/package_todo.yml
- tests/fixtures/contains_stale_violations/packs/foo/app/services/foo.rb
- tests/fixtures/contains_stale_violations/packs/foo/package.yml
- tests/fixtures/contains_stale_violations/packs/foo/package_todo.yml
- tests/fixtures/contains_stale_violations/packwerk.yml
- tests/update_test.rs
Closes #66 
This also permits the deletion of `package_todo.yml` where the entire file is stale.
- Create test fixture
- add failing test
- violations => found_violations
- use a hashset for violation identifiers
- rename var
- write another failing test
- make test pass maybe
- commit update to package todo
> Implement stale violations detection

- Cargo.toml
- src/packs/configuration.rs
- Allow custom_associations to accept Ruby symbols as values
- bump version
> Allow custom associations to accept symbols to be compatible with packwerk

- Cargo.toml
- src/packs/checker.rs
- tests/check_test.rs
There was an issue with the experimental parser where when given single files, it was unable to properly resolve constants.
This is because the experimental parser requires looking at *all* processed files to properly resolve constants.
To fix this, I *always* process all files with the experimental parser, but only analyze references related to the input files.
- add failing test
- refactor existing get_all_references function
- fix test
- bump version
> Fix bug with experimental parser and single file inputs

- Cargo.toml
- src/packs/raw_configuration.rs
- fix test
- improve error message
- bump version
> Allow packwerk.yml package_paths to be a single glob string

- Cargo.toml
- src/packs.rs
- src/packs/caching/mod.rs
- src/packs/caching/per_file_cache.rs
- src/packs/checker.rs
- src/packs/configuration.rs
- tests/delete_cache_test.rs
The idea here is the following:
- Originally, `packs` was attempting to provide a cache for the ruby `packwerk`, so we wanted to put the cache in the same location.
- Now, I wouldn't recommend using packs this way, and I don't think anyone is.
- The original implementation did a bunch of funny things to try to make the cache compatible with `packwerk`. We can remove this complexity by moving it into a separate folder.
- The experimental parser was *also* using the same folder. This made it really confusing to switch between the exerimental and non-experimental parsers, since they used the same cache locations but actually had incompatible cache data, even though the type shapes were compatible. This was really confusing and led to a sub-par experience.
- Caches should be in own folder
- …
> Have packs caches live in subfolder of tmp/cache/packwerk

- src/lib.rs
- src/packs.rs
- src/packs/checker.rs
- src/packs/parsing/erb/mod.rs
- src/packs/parsing/mod.rs
- src/packs/parsing/ruby/experimental.rs
- src/packs/parsing/ruby/mod.rs
- src/packs/parsing/ruby/zeitwerk/mod.rs
- src/packs/reference_extractor.rs
Updates visibility of modules and pulls out a "Reference extractor" module.
- add commands module
- reorganize imports
- make things private
- add comment
- reorganize other main imports
- reorganize library imports
- add ocmment
- reorganize other imports
- wip
- more module reorgs
- make things private
> Various tidying up

- Cargo.toml
- README.md
- src/packs/cli.rs
- src/packs/configuration.rs
- src/packs/file_utils.rs
- src/packs/parsing/erb/experimental/parser.rs
- src/packs/parsing/erb/packwerk/parser.rs
- src/packs/parsing/mod.rs
- src/packs/parsing/ruby/experimental/parser.rs
- src/packs/parsing/ruby/packwerk/parser.rs
- tests/check_test.rs
This PR implements a command that checks file contents piped though standard input. The command also takes a file path so that it knows where the file is supposed to be located and what constraints apply.
The intent is to use this command to implement as-you-type linters in IDEs.
```
$ cat foo/bar.rb | packs check-contents foo/bar.rb
```
This probably needs a test... 😄 Also not sure if cache handling is correct.
> Implement check-contents subcommand

- Cargo.toml
```
config = { a: { b: :c } }
config => a: {b:}
```
This syntax was unsupported.
See https://github.com/lib-ruby-parser/lib-ruby-parser/issues/85 for more info
> Bump lib-ruby-parser to fix panic when parsing certain pattern matching syntax

- Cargo.toml
- README.md
- src/packs.rs
- src/packs/cli.rs
- src/packs/file_utils.rs
- src/packs/monkey_patch_detection.rs
- src/packs/parsing/ruby/experimental/constant_resolver.rs
- src/packs/parsing/ruby/experimental/parser.rs
- src/packs/parsing/ruby/parse_utils.rs
- tests/expose_monkey_patches_test.rs
- tests/fixtures/app_with_monkey_patches/app/models/some_root_class.rb
- tests/fixtures/app_with_monkey_patches/app/services/some_root_class.rb
- tests/fixtures/app_with_monkey_patches/config/initializers/rails_monkeypatch.rb
- tests/fixtures/app_with_monkey_patches/gemdir_stub/activesupport/date.rb
- tests/fixtures/app_with_monkey_patches/gemdir_stub/activesupport/string.rb
- tests/fixtures/app_with_monkey_patches/gemdir_stub/rails/rails.rb
- tests/fixtures/app_with_monkey_patches/packwerk.yml
- tests/fixtures/app_with_monkey_patches/rubydir_stub/date.rb
- tests/fixtures/app_with_monkey_patches/rubydir_stub/string.rb
This implements an experimental feature to expose monkey patches, allowing a user to see where their application is monkey patching the ruby stdlib, gems they use, or itself.
With the experimental parser, I realized we could point it at various directories and compare definitions of the same constant to identify monkey patches.
Theoretically it can also be used to see gems they use that monkey patch the ruby stdlib or other gems.
I'm not sure if knowing this information is valuable to orgs, but I thought it was an interesting feature to explore!
> Implement `packs --experimental-parser expose-monkey-patches`

- src/packs/checker.rs
- src/packs/cli.rs
- src/packs/configuration.rs
- tests/check_test.rs
This adds a command-line option `--ignore-recorded-violations` to `check` and `check-contents` commands that skips filtering out recorded violations. This is especially useful in editor integrations to see all the violations, even those recorded in `package_todo.yml`.
> Add option to ignore recorded violations

- Cargo.toml
- src/packs/monkey_patch_detection.rs
When the output is saved to a markdown file, e.g.:
```
pks --experimental-parser expose-monkey-patches \
--rubydir=/Users/alex.evanczuk/.rbenv/versions/3.2.2/lib/ruby/3.2.0/ \
--gemdir=/Users/alex.evanczuk/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ \
> results.md
```
That markdown is a lot easier to read:
In the future, we could also add a `json` mode so the user can easily create their own formatters. For now, this is a helpful format to see the initial list.
- make test fail
- bump version
> Improve the output of expose monkey patches

- .github/workflows/ci.yml
- Cargo.toml
Fixes #107
- bump version
- Diff HEAD~1 and HEAD in the correct order
> Fix incorrect version number listed in releases

- Cargo.toml
- tests/update_test.rs
Helps resolve flaky test due to cleaning up a fixture-under-test while the other test is still running in parallel.
In the future, we can think of other designs to solve this non-determinism. For example:
- Each test gets its own fixture
- Testing something that doesn't mutate shared state
- etc.
> Run update tests in serial

- Cargo.toml
- src/packs/checker/dependency.rs
- src/packs/pack.rs
- tests/fixtures/contains_duplicates_in_package/packs/bar/app/models/concerns/some_concern.rb
- tests/fixtures/contains_duplicates_in_package/packs/bar/app/services/bar.rb
- tests/fixtures/contains_duplicates_in_package/packs/bar/package.yml
- tests/fixtures/contains_duplicates_in_package/packs/foo/package.yml
- tests/fixtures/contains_duplicates_in_package/packwerk.yml
Including the file name in the panic message.
Before
```
pks validate
thread 'main' panicked at src/packs/pack.rs:217:14:
Failed to deserialize the YAML: Error("duplicate field `enforce_architecture`", line: 1, column: 1)
```
After
```
thread 'main' panicked at src/packs/pack.rs:220:17:
Failed to deserialize the YAML at "/my/packs/foo/package.yml" with error: Error("duplicate field `enforce_architecture`", line: 1, column: 1)
```
> Providing descriptive panic message when a package.yml cannot be deserialized

- src/packs/checker/architecture.rs
- src/packs/checker/dependency.rs
Small PR addressing suggestion in https://github.com/alexevanczuk/packs/pull/127
Moving the architecture validation will come in a follow up PR.
> Renaming is_architecture_dependency to dependency_permitted for clarity

- src/packs/file_utils.rs
- src/packs/pack.rs
- src/packs/parsing/ruby/zeitwerk/mod.rs
Let packs own calculation of their autoload roots in order to simplify logic elsewhere.
> Simplify autoload root determination

- src/lib.rs
- src/packs.rs
- src/packs/checker/dependency.rs
- src/packs/configuration.rs
- src/packs/pack.rs
- src/packs/parsing/ruby/packwerk.rs
- src/packs/parsing/ruby/zeitwerk/mod.rs
- src/packs/raw_configuration.rs
- src/packs/reference_extractor.rs
- tests/fixtures/simple_app/app/company_data/widget.rb
- tests/fixtures/simple_app/packwerk.yml
Zeitwerk [supports defining root namespaces](https://github.com/fxn/zeitwerk?tab=readme-ov-file#zeitwerkloaderdirs) for autoload root directories. For example, maybe you want to nest all constants defined in `app/services` under the `CompanyName` domain. Under this rule, Zeitwerk would expect a file called `app/services/widget_maker.rb` to define a constant `::CompanyName::WidgetMaker` rather than just `WidgetMaker`.
This pull request allows us to teach `packs` about the overridden namespaces via a new configuration key `namespace_overrides`. It takes the autoload root dirs as keys and the name of the custom root namespace as the values. So for the above example, you'd need to specify the following in `packwerk.yml`:
```
namespace_overrides:
app/services: "::CompanyName"
```
Two things …
> Support custom root namespaces

- Cargo.toml
- src/packs/configuration.rs
- src/packs/walk_directory.rs
- tests/fixtures/simple_app/frontend/ui_helper.rb
**Background**:
We have a monolith containing ruby code in a top-level directory named `frontend`.
`packwerk check` includes `frontend` when looking for violations. 
**Change**
Do not ignore `frontend` by default. Developers can use the `packwerk.yml` -> `exclude:` section to ignore `frontend` if necessary.
> Do not ignore "frontend" dir

- src/lib.rs
- src/packs.rs
- src/packs/configuration.rs
- src/packs/constant_resolver.rs
- src/packs/parsing/ruby/rails_utils.rs
- src/packs/parsing/ruby/zeitwerk/mod.rs
- src/packs/raw_configuration.rs
- src/packs/reference_extractor.rs
In our monolith we have a custom name for our inflections file. As `packs` currently hard codes the inflections file to `config/initializers/inflections.rb`, our inflections are missed. This PR adds a new configuration parameter that allows users to specify an `inflections_path`.
This PR is best reviewed commit-by-commit. The first commit is most significant and refactors our parameters and creates a new `ConstantResolverConfiguration` struct to encapsulate the relevant parameters that are always passed around as a group anyway. The last commit adds the new `inflections_path` property and is pretty simple.
My only thought about this change is it might be better named `ConstantResolver::Configuration` but embarrassingly enough I wasn't sure the "right" way to do this and I wasn't sure …
> Support custom inflections file

- Cargo.toml
- src/packs/checker/dependency.rs
- tests/fixtures/app_with_dependency_cycles/packs/baz/package.yml
- tests/validate_test.rs
**Context:**
`packwerk` reports a validation error if a pack lists itself as a dependency.
pack/foo/package.yml
```yml
dependencies:
- packs/foo
```
However, the rust equivalent does not.
**Change:**
When a package.yml lists itself as dependency, `pks validate` now prints "Package cannot list itself as a dependency: packs/foo/package.yml"
> Adding validation errors for self-dependencies

- src/packs.rs
- src/packs/cli.rs
- src/packs/constant_dependencies.rs
- tests/add_constant_dependencies.rs
- tests/common/mod.rs
- tests/fixtures/app_with_missing_dependencies/packs/bar/app/public/bar/tender.rb
- tests/fixtures/app_with_missing_dependencies/packs/bar/package.yml
- tests/fixtures/app_with_missing_dependencies/packs/baz/app/services/baz/patron.rb
- tests/fixtures/app_with_missing_dependencies/packs/baz/package.yml
- tests/fixtures/app_with_missing_dependencies/packs/foo/app/services/foo/no_bar.rb
- tests/fixtures/app_with_missing_dependencies/packs/foo/package.yml
- tests/fixtures/app_with_missing_dependencies/packwerk.yml
**Context**
Say you moved a private constant `::Foo::Bar` to `app/public` in your `packs/foo` pack and other packs already refer to it. Without this change, you would need to track down all references to `::Foo::Bar` and add `packs/foo` to their `package.yml` dependencies.
**The Change**
`packs update-dependencies-for-constant ::Foo::Bar` will add a `packs/foo` dependency to all the applicable `package.yml` files
> Update dependencies for constant

- .github/workflows/ci.yml
- Cargo.toml
Why?
---
We want to incorporate `pks` into CI. 
What?
---
This change creates and uploads a linux binary to the "release".
Example
---
See https://github.com/perryqh/build-packs/releases/tag/v0.1.25 as an example of the linux binary.
Notes
---
I experimented with https://github.com/taiki-e/upload-rust-binary-action. I liked it as it would significantly reduce the code in ci.yml. However, I wanted to keep this PR small and we still would need the custom steps for uploading just `packs` and publishing to crates.io
> On release, upload a linux binary

- src/main-alt.rs
- src/main.rs
- src/packs.rs
- src/packs/checker.rs
- src/packs/cli.rs
- tests/add_constant_dependencies.rs
This PR aims to standardize the error handling across the codebase by adopting the [anyhow](https://docs.rs/anyhow/latest/anyhow/) crate, which was previously introduced due to its ergonomic advantages. The goal is to consistently utilize the anyhow Result type throughout the project.
A [good summary](https://antoinerr.github.io/blog-website/2023/01/28/rust-anyhow.html) of anyhow's advantages
Modified the entrypoint result types in `packs` to use [anyhow](https://docs.rs/anyhow/latest/anyhow/).
> Consistent "Result" types

- src/packs.rs
- src/packs/checker.rs
To support different output formats, It would be better to collect errors and decide how they should be rendered at a higher level.
Examples:
1. when using `packs` in CI, we might want packs to respond in a JSON format
2. we might want to surface a "check" API which returns the actual violations instead of printing them 
Printing "check" results in packs.rb rather than inline.
This PR builds off of https://github.com/alexevanczuk/packs/pull/152
> Collect check messages and print results 

- src/packs.rs
- src/packs/caching/cache.rs
- src/packs/caching/mod.rs
- src/packs/caching/noop_cache.rs
- src/packs/caching/per_file_cache.rs
- src/packs/checker.rs
- src/packs/cli.rs
- src/packs/constant_dependencies.rs
- src/packs/file_utils.rs
- src/packs/monkey_patch_detection.rs
- src/packs/parsing/mod.rs
- src/packs/reference_extractor.rs
Instead of "panic!", return anyhow::Result
This will give us better control to print friendly error messages and/or provide APIs
I tried to keep this PR small, but changing a result type kicks off a game of whack-a-mole.
> refactored some "panics" to instead return errors

- src/packs/checker.rs
- src/packs/checker/architecture.rs
- src/packs/checker/dependency.rs
- src/packs/checker/folder_visibility.rs
- src/packs/checker/privacy.rs
- src/packs/checker/visibility.rs
Removing some more `panic!`s in favor of bubbling up error results
> Returning anyhow::Result when checking for strictness violations and retrieving packs

- src/packs/file_utils.rs
- src/packs/parsing/erb/experimental/parser.rs
- src/packs/parsing/erb/packwerk/parser.rs
- src/packs/parsing/mod.rs
- src/packs/parsing/ruby/experimental/parser.rs
- src/packs/parsing/ruby/packwerk/parser.rs
Removing `panic` from `file_read_contents`
> file_read_contents returning anyhow::Result

- src/lib.rs
- src/packs.rs
- src/packs/caching/per_file_cache.rs
- src/packs/checker/architecture.rs
- src/packs/checker/dependency.rs
- src/packs/checker/privacy.rs
- src/packs/checker/visibility.rs
- src/packs/cli.rs
- src/packs/configuration.rs
- src/packs/constant_dependencies.rs
- src/packs/monkey_patch_detection.rs
- src/packs/pack_set.rs
- src/packs/parsing/ruby/zeitwerk/mod.rs
- tests/add_constant_dependencies.rs
- tests/add_dependency_test.rs
With this change, `Configuration` functions return `anyhow::Result`s instead of panicking.
In a subsequent PR, we might convert Configuration::default(), to `new` so it also can return a `Result` instead of panicking.
> Configuration returns anyhow::Result

- src/packs.rs
- src/packs/checker/reference.rs
- src/packs/pack_set.rs
- src/packs/reference_extractor.rs
Replacing the `panic` in `for_file` with a returned anyhow::Result
> for_file returns result

- src/packs/checker.rs
- src/packs/checker/architecture.rs
- src/packs/checker/dependency.rs
- src/packs/checker/folder_visibility.rs
- src/packs/checker/privacy.rs
- src/packs/checker/reference.rs
- src/packs/checker/visibility.rs
Rather than panic, `check` not returns an `anyhow::Result`
> check returns anyhow::Result

- src/packs.rs
- src/packs/checker.rs
Changed `build_stale_violations` to return errors instead of panicking
> Bubble up stale violation errors

- src/packs/checker.rs
- src/packs/checker/common_test.rs
- src/packs/checker/privacy.rs
Before changing `packs update` functionality as [outlined](https://github.com/alexevanczuk/packs/issues/166), DRYing up checker unit tests to have higher confidence in changes to `check`.
> DRYing up checker unit tests

- src/packs/checker.rs
- src/packs/checker/architecture.rs
- src/packs/checker/common_test.rs
- src/packs/checker/dependency.rs
- src/packs/checker/folder_visibility.rs
- src/packs/checker/privacy.rs
- src/packs/checker/visibility.rs
- src/packs/pack.rs
- src/packs/package_todo.rs
- tests/fixtures/contains_strict_violations/packs/bar/app/services/bar.rb
- tests/fixtures/contains_strict_violations/packs/bar/package.yml
- tests/fixtures/contains_strict_violations/packs/foo/app/services/foo.rb
- tests/fixtures/contains_strict_violations/packs/foo/package.yml
- tests/fixtures/contains_strict_violations/packwerk.yml
- tests/update_test.rs
Background
---
Strict violations always cause `pks check` failures. There's no need to write out strict violations to "todo" files.
Changes
---
> Not writing strict violations to todos

- Cargo.toml
- src/packs/checker.rs
- src/packs/checker/architecture.rs
- src/packs/checker/dependency.rs
- src/packs/checker/folder_visibility.rs
- src/packs/checker/privacy.rs
- src/packs/checker/visibility.rs
With the recent changes to when strict-mode is determined, the `is_strict_mode_violation` function became obsolete.
> Removing unused "strict-mode" code

- src/packs/checker.rs
- tests/check_unnecessary_dependencies.rs
Background
---
When the `check-unnecessary-dependencies` command finds unnecessary dependencies, it prints `List unnecessary dependencies failed`. This message can be confusing in that it might be unintentionally communicating that the command itself failed rather than unnecessary dependencies were found.
Change
---
Updates the message to clearly communicate that unnecessary dependencies were found.
> Providing a better check_unnecessary_dependencies error message

- Cargo.toml
- src/packs/checker/architecture.rs
If a `package.yml` specified an invalid 'layer', we want to handle it gracefully instead of panicking.
> Returning invalid layer error instead of panicking

- Cargo.toml
There's a weird issue right now where is a PR that bumped the version caused a failure to upload the binary, subsequent commits will fail. We think CI will go green again bumping the version since the release should be created. We could probably make CI/CD more robust but this should be fine for now.
> Bump version to get CI green again

- src/packs/pack.rs
- tests/corrupt_todo_test.rs
- tests/fixtures/contains_corrupt_todo/packs/bar/app/services/bar.rb
- tests/fixtures/contains_corrupt_todo/packs/bar/package.yml
- tests/fixtures/contains_corrupt_todo/packs/bar/package_todo.yml
- tests/fixtures/contains_corrupt_todo/packs/foo/app/services/foo.rb
- tests/fixtures/contains_corrupt_todo/packs/foo/package.yml
- tests/fixtures/contains_corrupt_todo/packs/foo/package_todo.yml
- tests/fixtures/contains_corrupt_todo/packwerk.yml
Context
---
A developer had a corrupt todo file and didn't know how to fix it. The corrupted todo file was likely caused by accidental "manual" edits to it.
Change
---
Updating the error message to include a solution for fixing their corrupt todo files.
> A better error message for corrupted todo files

- Cargo.toml
- src/packs/caching/per_file_cache.rs
We've seen a couple instances of corrupt cache. This change treats invalid cache the same as no cache so that pks can continue processing instead of erroring out and confusing users.
> If corrupt cache, log and move on

- src/packs/checker/architecture.rs
- tests/fixtures/app_with_architecture_violations_in_yml/packs/bar/package.yml
- tests/fixtures/app_with_architecture_violations_in_yml/packs/baz/package.yml
- tests/fixtures/app_with_architecture_violations_in_yml/packs/foo/package.yml
- tests/validate_test.rs
- if a layer is specified in a `package.yml`, it must be one of the layers defined in `packwerk.yml`
- if `enforce_architecture` is `true` or `strict`, a layer must be specified
- a packages' dependencies should not be used in layer validations. `check` will find layer violations
> Updating layer validations

- Cargo.toml
- src/packs/checker.rs
- tests/check_test.rs
- tests/fixtures/contains_stale_violations_no_file/packs/bar/app/services/bar.rb
- tests/fixtures/contains_stale_violations_no_file/packs/bar/package.yml
- tests/fixtures/contains_stale_violations_no_file/packs/bar/package_todo.yml
- tests/fixtures/contains_stale_violations_no_file/packs/foo/app/services/foo.rb
- tests/fixtures/contains_stale_violations_no_file/packs/foo/package.yml
- tests/fixtures/contains_stale_violations_no_file/packwerk.yml
We noticed that `packs check` doesn't report a violation as "stale" if the file no longer exists.
Example:
```yml
"::Item":
violations:
- dependency
files:
- packs/product_services/items/path/to/file_no_longer_exists.rb
```
If `file_no_longer_exists.rb` is deleted, `pks check` does not report it as stale.
Consider a violation stale if the file does not exist
> Fix stale check when deleted

- Cargo.toml
New 0.2.0 for `layer` violations.
> bumping to version 0.2.0

- .github/workflows/ci.yml
- Cargo.toml
Releasing an aarch64 linux binary
[Test](https://github.com/perryqh/packs-ci/releases/tag/v0.2.3)
> adding aarch64-linux-unknown release binary

- Cargo.toml
- src/packs/checker.rs
- src/packs/checker/common_test.rs
- src/packs/checker/dependency.rs
- src/packs/checker/folder_visibility.rs
- src/packs/checker/layer.rs
- src/packs/checker/output_helper.rs
- src/packs/checker/privacy.rs
- src/packs/checker/visibility.rs
- tests/architecture_violations_test.rs
- tests/check_test.rs
Much more readable
- **Make the file names blue like packwerk**
- **extract out helper**
- **fix common test to make it strip colors**
- **make one integration test strip colors**
- **update other tests**
- **version**
> Make file path cyan in output like packwerk

- .github/workflows/ci.yml
- .github/workflows/dotslash-config.json
We started using [dotslash](https://dotslash-cli.com/) to launch `pks`. We named the dotslash file `pks` and put it in the Rails `bin` directory. We now launch `pks` with `bin/pks`.
The reason we decided to take this approach was to ensure that the correct version of `pks` is always used and to provided a consistent installation for both mac and linux.
This PR use the `facebook/dotslash-publish-release@v1` github action to create and upload a dotslash file into the release assets. The file is simply named `pks`.
I also broke out a separate `upload-mac-binary` job that is run in parallel with `upload-linux-bin`
https://github.com/perryqh/packs-ci/releases/tag/v0.2.8
> Update ci to generate a dotslash file

- .github/workflows/ci.yml
I believe this [fixes](https://github.com/perryqh/packs-ci/actions/runs/9571584049) the CI pipeline when the Cargo.toml version hasn't changed.
> Simplifying new version check

- Cargo.toml
- README.md
- src/packs/checker/dependency.rs
- src/packs/checker/folder_privacy.rs
- src/packs/checker/layer.rs
- src/packs/checker/privacy.rs
- src/packs/checker/visibility.rs
- src/packs/pack.rs
Adding a new `reason` field to `enforcement_globs_ignore`
Example:
```yml
enforcement_globs_ignore:
- enforcements:
- privacy
- visiblity
ignores:
- "**/*"
- "!packs/product_services/serv1/**/*"
reason: "It was decided only to fix incoming violations from serv1. See ticket #232"
```
> Add reason to enforcement ignores

- Cargo.toml
- tests/create_test.rs
The `0.2.10` [test suite](https://github.com/alexevanczuk/packs/actions/runs/9718013657/job/26824933932) failed because of a timing issue.
I believe that `test_create_already_exists` ran before `test_create` had finished  `common::delete_foobar();`
`test_create_already_exists` now uses a different fixture
> Fixing create-when-exists race condition

- Cargo.toml
- src/packs.rs
- src/packs/cli.rs
- tests/common/mod.rs
- tests/init_test.rs
As discussed in #144 an init command might be nice. 
This is probably the first time I have ever written any Rust so I just tried copying things I saw in the existing implementation and did some work arounds to compile errors using ChatGPT. 
Ideally someone with some experience could help turn this into a proper solution that is more idiomatic etc!
I added the config file creation at a point before the configuration load happens to avoid it blowing up but Im sure there is a better solution here. 
Anyway thought it might be a starting point!
> Initial pass at an `init` command

- src/packs/parsing/ruby/experimental.rs
- src/packs/parsing/ruby/experimental/parser.rs
- src/packs/parsing/ruby/packwerk.rs
- src/packs/parsing/ruby/packwerk/parser.rs
I believe this fixes https://github.com/alexevanczuk/packs/issues/215.
`Bar::ADAPTER['default']::INSTANCE` is parsed as constant reference of `INSTANCE` with scope of `Bar::ADAPTER['default']`.
There used to be an assumption that if you encounter something other than a constant while recursing into the scope (in `fetch_const_const_name`), this constant reference should be ignored. However, we should instead recursively visit the scope to check if there any other constants there.
I thought of adding a test case for this, but I'm confused where to add it exactly.
<details>
<summary>Full AST of foo.rb</summary>
```rust
Class(
Class {
name: Const(
Const {
scope: None,
name: "Foo",
double_colon_l: None,
name_l: 6...9,
expression_l: 6...9,
},
),
superclass: None,
body: Some(
Def(
Def {
name: …
```
> Recurse into Const scope if unable to fetch const name

- Cargo.toml
- src/packs/checker/privacy.rs
- src/packs/parsing/ruby/mod.rs
- tests/public_sigil_test.rs
The packwerk extension doesn't work with pks implementation of the public sigil, because the input file is a single file and we need to process the defining file that contains the sigil in order to "register" the sigil.
Packwerk solves this problem by just opening up every file and checking for the sigil. I did not want to do this by default in pks because we already have a pass of reading files, and not reading files again helps keep pks snappy.
However, in the extension, we always have a very small number of input files, so we can have a hard-coded exception there to actually read the files in those cases to keep the extension working.
> pack_public sigil should work with extension – read files if input included files is small

- Cargo.toml
- src/packs/parsing/ruby/zeitwerk/mod.rs
There's a persistent issue I'm seeing, it looks like this:
```
$ pks update
thread 'main' panicked at /Users/alexevanczuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pks-0.2.21/src/packs/parsing/ruby/zeitwerk/mod.rs:293:41:
called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It appears that the `constant_resolver.json` cache file is just an empty string.
I don't know why that is – nothing in the process intentionally will write an empty string – it should at least write *something*.
I suspect it has to do with some race condition across multiple processes when using the extension.
I'm hoping adding a file-exclusive lock on the cache file will fix this. …
> Attempt to fix corrupted constant_resolver.json cache issue breaking pks update and pks check
